# Generated by Django 3.2.6 on 2021-08-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=7)),
                ('dev', models.CharField(max_length=10)),
            ],
        ),
    ]
