# Generated by Django 3.2.6 on 2021-08-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_mysql_app', '0002_auto_20210826_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtable',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
